### PR TITLE
Eliminate unnecessary features

### PR DESCRIPTION
**Pull request by asomers**
Several features have been added since the fork from serde_yaml that IMHO don't add any utility at all.  But they do bring in new dependencies, causing unnecessary bloat.  See individual commit messages for details.

### CODE REVIEW

**Review by sebastienrousseau — CHANGES_REQUESTED** [review]
@asomers Will you be able to merge your code to https://github.com/sebastienrousseau/serde_yml/pull/24? This way we can fix all the issues all together?

**Comment by asomers** [comment]
> @asomers Will you be able to merge your code to #24? This way we can fix all the issues all together?

I don't think so.  I don't think I have permission to update that PR.

**Comment by sebastienrousseau** [comment]
@asomers Ok, changes will be part of https://github.com/sebastienrousseau/serde_yml/pull/24

**Comment by sebastienrousseau** [comment]
@asomers and @evaneaston Changes merged to v0.0.7. Thanks!

**Pull request closed without merging**
